const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);let expr='',ans=0,angle='DEG',mode='basic';
const expression=$('#expression'),result=$('#result'),history=$('#history'),fractionBox=$('#fractionBox');
function render(){expression.textContent=expr||'0';result.textContent=expr?'':formatAnswer(ans);}
function formatNumber(n){if(!Number.isFinite(n))throw Error('القيمة غير صالحة');if(Math.abs(n)<1e-12)n=0;return Number(n.toFixed(12)).toString()}
function formatAnswer(n){if(!Number.isFinite(n))return 'خطأ';let s=formatNumber(n),d=1000000;for(let i=1;i<=1000;i++){let x=n*i;if(Math.abs(x-Math.round(x))<1e-9){d=i;break}}let num=Math.round(n*d);if(d>1&&Math.abs(n)<1e7)return `<span class="fraction-result"><span>${num}</span><span>${d}</span></span> <small>(${s})</small>`;return s}
function append(v){if(expr==='0'&&/^[0-9.]$/.test(v))expr='';expr+=v;result.textContent='';expression.textContent=expr}
function clear(){expr='';history.textContent='';render()}
function back(){expr=expr.slice(0,-1);render()}
function factorial(n){if(n<0||n>170||n%1)return NaN;let r=1;for(let i=2;i<=n;i++)r*=i;return r}
function tokenize(s){s=s.replaceAll('×','*').replaceAll('÷','/').replaceAll('−','-').replaceAll('π','PI').replaceAll('√','sqrt');let i=0,t=[];while(i<s.length){if(/\s/.test(s[i])){i++;continue}let m=s.slice(i).match(/^(?:\d+(?:\.\d*)?|\.\d+)(?:e[+-]?\d+)?/i);if(m){t.push({v:Number(m[0]),type:'num'});i+=m[0].length;continue}m=s.slice(i).match(/^(sin|cos|tan|asin|acos|atan|log|ln|sqrt|PI|E|e|ans)/i);if(m){t.push({v:m[0].toLowerCase(),type:'word'});i+=m[0].length;continue}if('+-*/^%!()'.includes(s[i])){t.push({v:s[i],type:'op'});i++;continue}throw Error('رمز غير معروف') }return t}
function evaluate(s){let t=tokenize(s),p=0;const peek=()=>t[p]?.v;function primary(){let v;if(peek()==='-'){p++;return-primary()}if(peek()==='('){p++;v=add();if(peek()!==')')throw Error('قوس ناقص');p++;return v}let z=t[p++];if(!z)throw Error('تعبير ناقص');if(z.type==='num')v=z.v;else if(z.v==='pi')v=Math.PI;else if(z.v==='e')v=Math.E;else if(z.v==='ans')v=ans;else throw Error('دالة ناقصة');return v}function post(){let v=primary();while(peek()==='!'){p++;v=factorial(v)}if(peek()==='%'){p++;v/=100}return v}function power(){let v=post();if(peek()==='^'){p++;v=Math.pow(v,power())}return v}function unary(){let f=peek();if(['sin','cos','tan','asin','acos','atan','log','ln','sqrt'].includes(f)){p++;if(peek()==='('){p++;let v=add();if(peek()!==')')throw Error('قوس ناقص');p++;return fn(f,v)}return fn(f,power())}return power()}function mul(){let v=unary();while(peek()==='*'||peek()==='/'){let o=t[p++].v,b=unary();if(o==='/'&&b===0)throw Error('لا يمكن القسمة على صفر');v=o==='*'?v*b:v/b}return v}function add(){let v=mul();while(peek()==='+'||peek()==='-'){let o=t[p++].v,b=mul();v=o==='+'?v+b:v-b}return v}function fn(f,v){let r=angle==='DEG'?Math.PI/180:1;if(f==='sin')return Math.sin(v*r);if(f==='cos')return Math.cos(v*r);if(f==='tan')return Math.tan(v*r);if(f==='asin')return Math.asin(v)/r;if(f==='acos')return Math.acos(v)/r;if(f==='atan')return Math.atan(v)/r;if(f==='log')return Math.log10(v);if(f==='ln')return Math.log(v);return Math.sqrt(v)}let v=add();if(p<t.length)throw Error('تعبير غير صحيح');return v}
function calculate(){if(!expr)return;try{let v=evaluate(expr);history.textContent=expr+' =';ans=v;expr='';result.innerHTML=formatAnswer(v)}catch(e){result.textContent=e.message;}}
function openFraction(){fractionBox.classList.remove('hidden');$('#numerator').value=expr;$('#denominator').focus()}
$('#applyFraction').onclick=()=>{let n=$('#numerator').value,d=$('#denominator').value;if(!n||!d||Number(d)===0){result.textContent='أدخل بسطاً ومقاماً صالحين';return}expr=`(${n})÷(${d})`;fractionBox.classList.add('hidden');calculate()};
$$('[data-value]').forEach(b=>b.onclick=()=>append(b.dataset.value));$$('[data-action="clear"]').forEach(b=>b.onclick=clear);$$('[data-action="backspace"]').forEach(b=>b.onclick=back);$$('[data-action="equals"]').forEach(b=>b.onclick=calculate);$$('[data-action="fraction"]').forEach(b=>b.onclick=openFraction);$$('[data-action="ans"]').forEach(b=>b.onclick=()=>append('ans'));
$$('.mode').forEach(b=>b.onclick=()=>{$$('.mode').forEach(x=>x.classList.remove('active'));b.classList.add('active');mode=b.dataset.mode;$('#scientificPad').classList.toggle('hidden',mode!=='scientific')});$('#angleBtn').onclick=()=>{angle=angle==='DEG'?'RAD':'DEG';$('#angleBtn').textContent=angle};$('#themeBtn').onclick=()=>document.body.classList.toggle('light');document.addEventListener('keydown',e=>{if(/[0-9.+\-*/()^%]/.test(e.key))append(e.key);if(e.key==='Enter')calculate();if(e.key==='Backspace')back();if(e.key==='Escape')clear()});render();
